In [3]:
import numpy as np
var = np.array([[1,2,3],[2,4,5]])
print (1.0/var)
print (var**3)
x = np.array([1,0,2])
print (x * var**2)

[[1.         0.5        0.33333333]
 [0.5        0.25       0.2       ]]
[[  1   8  27]
 [  8  64 125]]
[[ 1  0 18]
 [ 4  0 50]]


In [5]:
import numpy as np
x = np.array([[1,2,3],[2,4,3]])
for i in range(x.shape[0]):
    print ('max: ',np.max(x[i,:]))
    print ('argmax: ', np.argmax(x[i,:]))

print('arg: ', np.argmax(x))
print('arg2: ', np.argmax(x, axis=0))

max:  3
argmax:  2
max:  4
argmax:  1
arg:  4
arg2:  [1 1 0]


In [6]:
import numpy as np
x = np.array([[[1],[2],[3]],[[2],[4],[3]]])
print('arg: ', np.argmax(x))
print('arg2: ', np.argmax(x, axis=0))
print('arg3: ', np.argmax(x[0,...]))
print('arg4; ', np.argmax(x[0,...], axis=1))
      

arg:  4
arg2:  [[1]
 [1]
 [0]]
arg3:  2
arg4;  [0 0 0]


In [7]:
import numpy as np
x = np.array([[[1,2],[3,4]],[[2,4],[3,5]]])
print(np.argmax(x[1,:]))

3


NameError: name 'log' is not defined

In [2]:
import numpy as np
x = np.array([[1,2,3],[2,34,4]])
a = np.sum(x, axis = 0)
b = np.sum(x, axis=1)
print (a)
print (b)

[ 3 36  7]
[ 6 40]


In [5]:
import numpy as np
a = np.random.ramdom_sample()
a *= 5.0
print (int(a))

AttributeError: module 'numpy.random' has no attribute 'ramdom_sample'

In [7]:
import numpy as np
print(int(5*np.random.random_sample()))

3
